name: jsmet
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - matplotlib>=3.3.2
  - cdsapi>=0.5.1
  - numpy>=1.21.2
  - dask
  - netCDF4>=1.5.5.1
  - bottleneck
  - scipy>=1.5.3
  - Cartopy>=0.18.0
  - pip>=21.1
  # Testing and development dependencies
  - black
  - coverage
  - flake8
  - parameterized
  - pre_commit
  - pylint
  - pytest
  - pip:
      - xarray>=0.19.0
      - cf_xarray
      - Shapely
