name: jsmet
channels:
    - conda-forge
    - default
dependencies:
    - xarray>=0.2
    - cf_xarray>=0.6.1
    - numpy>=1.17
    - scipy>=1.2
    - numba
    - pandas>=1.1
    - cftime>=1.4.1
    - dask>=2.6.0
    - netCDF4>=1.5.5.1
    - bottleneck>=1.3.1,<1.4
    - matplotlib>=3.3.2
    - cdsapi>=0.5.1
    - shapely
    # Testing and development dependencies
    - black
    - coverage
    - flake8
    - parameterized
    - pre_commit
    - pylint
    - pytest