name: jsmet
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib==3.3.2
  - numpy==1.19.2
  - dask
  - netcdf4
  - bottleneck
  - scipy
  - Cartopy==0.18.0
  - pip
  - pip:
     - xarray
