name: jsmet
channels:
  - conda-forge
  - default
dependencies:
  - python>=3.8
  - xarray>=0.21.2
  - cf_xarray>=0.6.1
  - numpy>=1.21.2,<=1.26.4
  - scipy>=1.2
  - numba
  - pandas>=1.1
  - cftime>=1.4.1
  - dask>=2.6.0
  - netCDF4
  - bottleneck
  - matplotlib>=3.3.2
  - cdsapi>=0.5.1
  # Testing and development dependencies
  - black
  - coverage
  - flake8
  - bump2version
  - pre_commit
  - pylint
  - pip
  - pip:
      - shapely
      - pytest-cov
      - parameterized
