name: jsmet
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib==3.3.2
  - numpy
  - dask
  - netCDF4==1.5.5.1
  - bottleneck
  - scipy==1.5.3
  - Cartopy==0.18.0
  - pip==21.1
  - pip:
     - xarray==0.17.0
